# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: updates.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rupdates.proto\")\n\x06Update\x12\r\n\x05price\x18\x01 \x01(\r\x12\x10\n\x08quantity\x18\x02 \x01(\r\"\"\n\tUpdateRow\x12\x15\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x07.Update\">\n\x13UpdateRowWithShares\x12\x17\n\x03row\x18\x01 \x01(\x0b\x32\n.UpdateRow\x12\x0e\n\x06shares\x18\x02 \x01(\r\"-\n\x07Updates\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.UpdateRowWithSharesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'updates_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATE._serialized_start=17
  _UPDATE._serialized_end=58
  _UPDATEROW._serialized_start=60
  _UPDATEROW._serialized_end=94
  _UPDATEROWWITHSHARES._serialized_start=96
  _UPDATEROWWITHSHARES._serialized_end=158
  _UPDATES._serialized_start=160
  _UPDATES._serialized_end=205
# @@protoc_insertion_point(module_scope)
