// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: updates.proto
// Protobuf C++ Version: 6.30.2

#ifndef updates_2eproto_2epb_2eh
#define updates_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_updates_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_updates_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_updates_2eproto;
}  // extern "C"
namespace orderbookio {
class Update;
struct UpdateDefaultTypeInternal;
extern UpdateDefaultTypeInternal _Update_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Update_class_data_;
class UpdateRow;
struct UpdateRowDefaultTypeInternal;
extern UpdateRowDefaultTypeInternal _UpdateRow_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UpdateRow_class_data_;
class UpdateRowWithShares;
struct UpdateRowWithSharesDefaultTypeInternal;
extern UpdateRowWithSharesDefaultTypeInternal _UpdateRowWithShares_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UpdateRowWithShares_class_data_;
class Updates;
struct UpdatesDefaultTypeInternal;
extern UpdatesDefaultTypeInternal _Updates_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Updates_class_data_;
}  // namespace orderbookio
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace orderbookio {

// ===================================================================


// -------------------------------------------------------------------

class Update final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:orderbookio.Update) */ {
 public:
  inline Update() : Update(nullptr) {}
  ~Update() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Update* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Update));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Update(::google::protobuf::internal::ConstantInitialized);

  inline Update(const Update& from) : Update(nullptr, from) {}
  inline Update(Update&& from) noexcept
      : Update(nullptr, std::move(from)) {}
  inline Update& operator=(const Update& from) {
    CopyFrom(from);
    return *this;
  }
  inline Update& operator=(Update&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Update& default_instance() {
    return *reinterpret_cast<const Update*>(
        &_Update_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Update& a, Update& b) { a.Swap(&b); }
  inline void Swap(Update* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Update* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Update* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Update>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Update& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Update& from) { Update::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Update* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "orderbookio.Update"; }

 protected:
  explicit Update(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Update(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Update& from);
  Update(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Update&& from) noexcept
      : Update(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPriceFieldNumber = 1,
    kQuantityFieldNumber = 2,
  };
  // uint32 price = 1;
  void clear_price() ;
  ::uint32_t price() const;
  void set_price(::uint32_t value);

  private:
  ::uint32_t _internal_price() const;
  void _internal_set_price(::uint32_t value);

  public:
  // uint32 quantity = 2;
  void clear_quantity() ;
  ::uint32_t quantity() const;
  void set_quantity(::uint32_t value);

  private:
  ::uint32_t _internal_quantity() const;
  void _internal_set_quantity(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:orderbookio.Update)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Update& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t price_;
    ::uint32_t quantity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_updates_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Update_class_data_;
// -------------------------------------------------------------------

class UpdateRow final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:orderbookio.UpdateRow) */ {
 public:
  inline UpdateRow() : UpdateRow(nullptr) {}
  ~UpdateRow() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UpdateRow* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UpdateRow));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateRow(::google::protobuf::internal::ConstantInitialized);

  inline UpdateRow(const UpdateRow& from) : UpdateRow(nullptr, from) {}
  inline UpdateRow(UpdateRow&& from) noexcept
      : UpdateRow(nullptr, std::move(from)) {}
  inline UpdateRow& operator=(const UpdateRow& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateRow& operator=(UpdateRow&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateRow& default_instance() {
    return *reinterpret_cast<const UpdateRow*>(
        &_UpdateRow_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(UpdateRow& a, UpdateRow& b) { a.Swap(&b); }
  inline void Swap(UpdateRow* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateRow* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateRow* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UpdateRow>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UpdateRow& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UpdateRow& from) { UpdateRow::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UpdateRow* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "orderbookio.UpdateRow"; }

 protected:
  explicit UpdateRow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UpdateRow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UpdateRow& from);
  UpdateRow(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UpdateRow&& from) noexcept
      : UpdateRow(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated .orderbookio.Update data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;

  public:
  void clear_data() ;
  ::orderbookio::Update* PROTOBUF_NONNULL mutable_data(int index);
  ::google::protobuf::RepeatedPtrField<::orderbookio::Update>* PROTOBUF_NONNULL mutable_data();

  private:
  const ::google::protobuf::RepeatedPtrField<::orderbookio::Update>& _internal_data() const;
  ::google::protobuf::RepeatedPtrField<::orderbookio::Update>* PROTOBUF_NONNULL _internal_mutable_data();
  public:
  const ::orderbookio::Update& data(int index) const;
  ::orderbookio::Update* PROTOBUF_NONNULL add_data();
  const ::google::protobuf::RepeatedPtrField<::orderbookio::Update>& data() const;
  // @@protoc_insertion_point(class_scope:orderbookio.UpdateRow)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UpdateRow& from_msg);
    ::google::protobuf::RepeatedPtrField< ::orderbookio::Update > data_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_updates_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UpdateRow_class_data_;
// -------------------------------------------------------------------

class UpdateRowWithShares final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:orderbookio.UpdateRowWithShares) */ {
 public:
  inline UpdateRowWithShares() : UpdateRowWithShares(nullptr) {}
  ~UpdateRowWithShares() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UpdateRowWithShares* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UpdateRowWithShares));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateRowWithShares(::google::protobuf::internal::ConstantInitialized);

  inline UpdateRowWithShares(const UpdateRowWithShares& from) : UpdateRowWithShares(nullptr, from) {}
  inline UpdateRowWithShares(UpdateRowWithShares&& from) noexcept
      : UpdateRowWithShares(nullptr, std::move(from)) {}
  inline UpdateRowWithShares& operator=(const UpdateRowWithShares& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateRowWithShares& operator=(UpdateRowWithShares&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateRowWithShares& default_instance() {
    return *reinterpret_cast<const UpdateRowWithShares*>(
        &_UpdateRowWithShares_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(UpdateRowWithShares& a, UpdateRowWithShares& b) { a.Swap(&b); }
  inline void Swap(UpdateRowWithShares* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateRowWithShares* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateRowWithShares* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UpdateRowWithShares>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UpdateRowWithShares& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UpdateRowWithShares& from) { UpdateRowWithShares::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UpdateRowWithShares* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "orderbookio.UpdateRowWithShares"; }

 protected:
  explicit UpdateRowWithShares(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UpdateRowWithShares(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UpdateRowWithShares& from);
  UpdateRowWithShares(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UpdateRowWithShares&& from) noexcept
      : UpdateRowWithShares(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRowFieldNumber = 1,
    kSharesFieldNumber = 2,
  };
  // .orderbookio.UpdateRow row = 1;
  bool has_row() const;
  void clear_row() ;
  const ::orderbookio::UpdateRow& row() const;
  [[nodiscard]] ::orderbookio::UpdateRow* PROTOBUF_NULLABLE release_row();
  ::orderbookio::UpdateRow* PROTOBUF_NONNULL mutable_row();
  void set_allocated_row(::orderbookio::UpdateRow* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_row(::orderbookio::UpdateRow* PROTOBUF_NULLABLE value);
  ::orderbookio::UpdateRow* PROTOBUF_NULLABLE unsafe_arena_release_row();

  private:
  const ::orderbookio::UpdateRow& _internal_row() const;
  ::orderbookio::UpdateRow* PROTOBUF_NONNULL _internal_mutable_row();

  public:
  // uint32 shares = 2;
  void clear_shares() ;
  ::uint32_t shares() const;
  void set_shares(::uint32_t value);

  private:
  ::uint32_t _internal_shares() const;
  void _internal_set_shares(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:orderbookio.UpdateRowWithShares)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UpdateRowWithShares& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::orderbookio::UpdateRow* PROTOBUF_NULLABLE row_;
    ::uint32_t shares_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_updates_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UpdateRowWithShares_class_data_;
// -------------------------------------------------------------------

class Updates final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:orderbookio.Updates) */ {
 public:
  inline Updates() : Updates(nullptr) {}
  ~Updates() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Updates* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Updates));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Updates(::google::protobuf::internal::ConstantInitialized);

  inline Updates(const Updates& from) : Updates(nullptr, from) {}
  inline Updates(Updates&& from) noexcept
      : Updates(nullptr, std::move(from)) {}
  inline Updates& operator=(const Updates& from) {
    CopyFrom(from);
    return *this;
  }
  inline Updates& operator=(Updates&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Updates& default_instance() {
    return *reinterpret_cast<const Updates*>(
        &_Updates_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Updates& a, Updates& b) { a.Swap(&b); }
  inline void Swap(Updates* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Updates* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Updates* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Updates>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Updates& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Updates& from) { Updates::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Updates* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "orderbookio.Updates"; }

 protected:
  explicit Updates(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Updates(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Updates& from);
  Updates(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Updates&& from) noexcept
      : Updates(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated .orderbookio.UpdateRowWithShares data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;

  public:
  void clear_data() ;
  ::orderbookio::UpdateRowWithShares* PROTOBUF_NONNULL mutable_data(int index);
  ::google::protobuf::RepeatedPtrField<::orderbookio::UpdateRowWithShares>* PROTOBUF_NONNULL mutable_data();

  private:
  const ::google::protobuf::RepeatedPtrField<::orderbookio::UpdateRowWithShares>& _internal_data() const;
  ::google::protobuf::RepeatedPtrField<::orderbookio::UpdateRowWithShares>* PROTOBUF_NONNULL _internal_mutable_data();
  public:
  const ::orderbookio::UpdateRowWithShares& data(int index) const;
  ::orderbookio::UpdateRowWithShares* PROTOBUF_NONNULL add_data();
  const ::google::protobuf::RepeatedPtrField<::orderbookio::UpdateRowWithShares>& data() const;
  // @@protoc_insertion_point(class_scope:orderbookio.Updates)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Updates& from_msg);
    ::google::protobuf::RepeatedPtrField< ::orderbookio::UpdateRowWithShares > data_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_updates_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Updates_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Update

// uint32 price = 1;
inline void Update::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t Update::price() const {
  // @@protoc_insertion_point(field_get:orderbookio.Update.price)
  return _internal_price();
}
inline void Update::set_price(::uint32_t value) {
  _internal_set_price(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:orderbookio.Update.price)
}
inline ::uint32_t Update::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_;
}
inline void Update::_internal_set_price(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = value;
}

// uint32 quantity = 2;
inline void Update::clear_quantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantity_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t Update::quantity() const {
  // @@protoc_insertion_point(field_get:orderbookio.Update.quantity)
  return _internal_quantity();
}
inline void Update::set_quantity(::uint32_t value) {
  _internal_set_quantity(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:orderbookio.Update.quantity)
}
inline ::uint32_t Update::_internal_quantity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.quantity_;
}
inline void Update::_internal_set_quantity(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantity_ = value;
}

// -------------------------------------------------------------------

// UpdateRow

// repeated .orderbookio.Update data = 1;
inline int UpdateRow::_internal_data_size() const {
  return _internal_data().size();
}
inline int UpdateRow::data_size() const {
  return _internal_data_size();
}
inline void UpdateRow::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Clear();
}
inline ::orderbookio::Update* PROTOBUF_NONNULL UpdateRow::mutable_data(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:orderbookio.UpdateRow.data)
  return _internal_mutable_data()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::orderbookio::Update>* PROTOBUF_NONNULL UpdateRow::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:orderbookio.UpdateRow.data)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_data();
}
inline const ::orderbookio::Update& UpdateRow::data(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:orderbookio.UpdateRow.data)
  return _internal_data().Get(index);
}
inline ::orderbookio::Update* PROTOBUF_NONNULL UpdateRow::add_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::orderbookio::Update* _add = _internal_mutable_data()->Add();
  // @@protoc_insertion_point(field_add:orderbookio.UpdateRow.data)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::orderbookio::Update>& UpdateRow::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:orderbookio.UpdateRow.data)
  return _internal_data();
}
inline const ::google::protobuf::RepeatedPtrField<::orderbookio::Update>&
UpdateRow::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_;
}
inline ::google::protobuf::RepeatedPtrField<::orderbookio::Update>* PROTOBUF_NONNULL
UpdateRow::_internal_mutable_data() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.data_;
}

// -------------------------------------------------------------------

// UpdateRowWithShares

// .orderbookio.UpdateRow row = 1;
inline bool UpdateRowWithShares::has_row() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.row_ != nullptr);
  return value;
}
inline void UpdateRowWithShares::clear_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.row_ != nullptr) _impl_.row_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::orderbookio::UpdateRow& UpdateRowWithShares::_internal_row() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::orderbookio::UpdateRow* p = _impl_.row_;
  return p != nullptr ? *p : reinterpret_cast<const ::orderbookio::UpdateRow&>(::orderbookio::_UpdateRow_default_instance_);
}
inline const ::orderbookio::UpdateRow& UpdateRowWithShares::row() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:orderbookio.UpdateRowWithShares.row)
  return _internal_row();
}
inline void UpdateRowWithShares::unsafe_arena_set_allocated_row(
    ::orderbookio::UpdateRow* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.row_);
  }
  _impl_.row_ = reinterpret_cast<::orderbookio::UpdateRow*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:orderbookio.UpdateRowWithShares.row)
}
inline ::orderbookio::UpdateRow* PROTOBUF_NULLABLE UpdateRowWithShares::release_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::orderbookio::UpdateRow* released = _impl_.row_;
  _impl_.row_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::orderbookio::UpdateRow* PROTOBUF_NULLABLE UpdateRowWithShares::unsafe_arena_release_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:orderbookio.UpdateRowWithShares.row)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::orderbookio::UpdateRow* temp = _impl_.row_;
  _impl_.row_ = nullptr;
  return temp;
}
inline ::orderbookio::UpdateRow* PROTOBUF_NONNULL UpdateRowWithShares::_internal_mutable_row() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.row_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::orderbookio::UpdateRow>(GetArena());
    _impl_.row_ = reinterpret_cast<::orderbookio::UpdateRow*>(p);
  }
  return _impl_.row_;
}
inline ::orderbookio::UpdateRow* PROTOBUF_NONNULL UpdateRowWithShares::mutable_row()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::orderbookio::UpdateRow* _msg = _internal_mutable_row();
  // @@protoc_insertion_point(field_mutable:orderbookio.UpdateRowWithShares.row)
  return _msg;
}
inline void UpdateRowWithShares::set_allocated_row(::orderbookio::UpdateRow* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.row_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.row_ = reinterpret_cast<::orderbookio::UpdateRow*>(value);
  // @@protoc_insertion_point(field_set_allocated:orderbookio.UpdateRowWithShares.row)
}

// uint32 shares = 2;
inline void UpdateRowWithShares::clear_shares() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shares_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t UpdateRowWithShares::shares() const {
  // @@protoc_insertion_point(field_get:orderbookio.UpdateRowWithShares.shares)
  return _internal_shares();
}
inline void UpdateRowWithShares::set_shares(::uint32_t value) {
  _internal_set_shares(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:orderbookio.UpdateRowWithShares.shares)
}
inline ::uint32_t UpdateRowWithShares::_internal_shares() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.shares_;
}
inline void UpdateRowWithShares::_internal_set_shares(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shares_ = value;
}

// -------------------------------------------------------------------

// Updates

// repeated .orderbookio.UpdateRowWithShares data = 1;
inline int Updates::_internal_data_size() const {
  return _internal_data().size();
}
inline int Updates::data_size() const {
  return _internal_data_size();
}
inline void Updates::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Clear();
}
inline ::orderbookio::UpdateRowWithShares* PROTOBUF_NONNULL Updates::mutable_data(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:orderbookio.Updates.data)
  return _internal_mutable_data()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::orderbookio::UpdateRowWithShares>* PROTOBUF_NONNULL Updates::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:orderbookio.Updates.data)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_data();
}
inline const ::orderbookio::UpdateRowWithShares& Updates::data(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:orderbookio.Updates.data)
  return _internal_data().Get(index);
}
inline ::orderbookio::UpdateRowWithShares* PROTOBUF_NONNULL Updates::add_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::orderbookio::UpdateRowWithShares* _add = _internal_mutable_data()->Add();
  // @@protoc_insertion_point(field_add:orderbookio.Updates.data)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::orderbookio::UpdateRowWithShares>& Updates::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:orderbookio.Updates.data)
  return _internal_data();
}
inline const ::google::protobuf::RepeatedPtrField<::orderbookio::UpdateRowWithShares>&
Updates::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_;
}
inline ::google::protobuf::RepeatedPtrField<::orderbookio::UpdateRowWithShares>* PROTOBUF_NONNULL
Updates::_internal_mutable_data() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.data_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace orderbookio


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // updates_2eproto_2epb_2eh
