// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: updates.proto
// Protobuf C++ Version: 6.30.2

#include "updates.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace orderbookio {

inline constexpr Update::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        price_{0u},
        quantity_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Update::Update(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Update_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateDefaultTypeInternal() {}
  union {
    Update _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateDefaultTypeInternal _Update_default_instance_;

inline constexpr UpdateRow::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateRow::UpdateRow(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UpdateRow_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateRowDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateRowDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateRowDefaultTypeInternal() {}
  union {
    UpdateRow _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateRowDefaultTypeInternal _UpdateRow_default_instance_;

inline constexpr UpdateRowWithShares::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        row_{nullptr},
        shares_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateRowWithShares::UpdateRowWithShares(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UpdateRowWithShares_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateRowWithSharesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateRowWithSharesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateRowWithSharesDefaultTypeInternal() {}
  union {
    UpdateRowWithShares _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateRowWithSharesDefaultTypeInternal _UpdateRowWithShares_default_instance_;

inline constexpr Updates::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Updates::Updates(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Updates_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdatesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdatesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdatesDefaultTypeInternal() {}
  union {
    Updates _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdatesDefaultTypeInternal _Updates_default_instance_;
}  // namespace orderbookio
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_updates_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_updates_2eproto = nullptr;
const ::uint32_t
    TableStruct_updates_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::orderbookio::Update, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::orderbookio::Update, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::orderbookio::Update, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::orderbookio::Update, _impl_.quantity_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::orderbookio::UpdateRow, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::orderbookio::UpdateRow, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::orderbookio::UpdateRowWithShares, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::orderbookio::UpdateRowWithShares, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::orderbookio::UpdateRowWithShares, _impl_.row_),
        PROTOBUF_FIELD_OFFSET(::orderbookio::UpdateRowWithShares, _impl_.shares_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::orderbookio::Updates, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::orderbookio::Updates, _impl_.data_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::orderbookio::Update)},
        {12, -1, -1, sizeof(::orderbookio::UpdateRow)},
        {21, 31, -1, sizeof(::orderbookio::UpdateRowWithShares)},
        {33, -1, -1, sizeof(::orderbookio::Updates)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::orderbookio::_Update_default_instance_._instance,
    &::orderbookio::_UpdateRow_default_instance_._instance,
    &::orderbookio::_UpdateRowWithShares_default_instance_._instance,
    &::orderbookio::_Updates_default_instance_._instance,
};
const char descriptor_table_protodef_updates_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rupdates.proto\022\013orderbookio\")\n\006Update\022\r"
    "\n\005price\030\001 \001(\r\022\020\n\010quantity\030\002 \001(\r\".\n\tUpdat"
    "eRow\022!\n\004data\030\001 \003(\0132\023.orderbookio.Update\""
    "J\n\023UpdateRowWithShares\022#\n\003row\030\001 \001(\0132\026.or"
    "derbookio.UpdateRow\022\016\n\006shares\030\002 \001(\r\"9\n\007U"
    "pdates\022.\n\004data\030\001 \003(\0132 .orderbookio.Updat"
    "eRowWithSharesb\006proto3"
};
static ::absl::once_flag descriptor_table_updates_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_updates_2eproto = {
    false,
    false,
    262,
    descriptor_table_protodef_updates_2eproto,
    "updates.proto",
    &descriptor_table_updates_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_updates_2eproto::offsets,
    file_level_enum_descriptors_updates_2eproto,
    file_level_service_descriptors_updates_2eproto,
};
namespace orderbookio {
// ===================================================================

class Update::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Update>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Update, _impl_._has_bits_);
};

Update::Update(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Update_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:orderbookio.Update)
}
Update::Update(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Update& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Update_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Update::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Update::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           0,
           offsetof(Impl_, quantity_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::quantity_));
}
Update::~Update() {
  // @@protoc_insertion_point(destructor:orderbookio.Update)
  SharedDtor(*this);
}
inline void Update::SharedDtor(MessageLite& self) {
  Update& this_ = static_cast<Update&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Update::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Update(arena);
}
constexpr auto Update::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Update),
                                            alignof(Update));
}
constexpr auto Update::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Update_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Update::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Update>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Update::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Update>(), &Update::ByteSizeLong,
              &Update::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Update, _impl_._cached_size_),
          false,
      },
      &Update::kDescriptorMethods,
      &descriptor_table_updates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Update_class_data_ =
        Update::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL Update::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Update_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Update_class_data_.tc_table);
  return Update_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
Update::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Update, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Update_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::orderbookio::Update>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 quantity = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Update, _impl_.quantity_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Update, _impl_.quantity_)}},
    // uint32 price = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Update, _impl_.price_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Update, _impl_.price_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 price = 1;
    {PROTOBUF_FIELD_OFFSET(Update, _impl_.price_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 quantity = 2;
    {PROTOBUF_FIELD_OFFSET(Update, _impl_.quantity_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Update::Clear() {
// @@protoc_insertion_point(message_clear_start:orderbookio.Update)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.price_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.quantity_) -
        reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.quantity_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Update::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Update& this_ = static_cast<const Update&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Update::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Update& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:orderbookio.Update)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 price = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_price() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_price(), target);
    }
  }

  // uint32 quantity = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_quantity() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_quantity(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:orderbookio.Update)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Update::ByteSizeLong(const MessageLite& base) {
  const Update& this_ = static_cast<const Update&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Update::ByteSizeLong() const {
  const Update& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:orderbookio.Update)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // uint32 price = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_price() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_price());
      }
    }
    // uint32 quantity = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_quantity() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_quantity());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Update::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Update*>(&to_msg);
  auto& from = static_cast<const Update&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:orderbookio.Update)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_price() != 0) {
        _this->_impl_.price_ = from._impl_.price_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_quantity() != 0) {
        _this->_impl_.quantity_ = from._impl_.quantity_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Update::CopyFrom(const Update& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:orderbookio.Update)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Update::InternalSwap(Update* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Update, _impl_.quantity_)
      + sizeof(Update::_impl_.quantity_)
      - PROTOBUF_FIELD_OFFSET(Update, _impl_.price_)>(
          reinterpret_cast<char*>(&_impl_.price_),
          reinterpret_cast<char*>(&other->_impl_.price_));
}

::google::protobuf::Metadata Update::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateRow::_Internal {
 public:
};

UpdateRow::UpdateRow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UpdateRow_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:orderbookio.UpdateRow)
}
PROTOBUF_NDEBUG_INLINE UpdateRow::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::orderbookio::UpdateRow& from_msg)
      : data_{visibility, arena, from.data_},
        _cached_size_{0} {}

UpdateRow::UpdateRow(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UpdateRow& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UpdateRow_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateRow* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:orderbookio.UpdateRow)
}
PROTOBUF_NDEBUG_INLINE UpdateRow::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : data_{visibility, arena},
        _cached_size_{0} {}

inline void UpdateRow::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UpdateRow::~UpdateRow() {
  // @@protoc_insertion_point(destructor:orderbookio.UpdateRow)
  SharedDtor(*this);
}
inline void UpdateRow::SharedDtor(MessageLite& self) {
  UpdateRow& this_ = static_cast<UpdateRow&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UpdateRow::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UpdateRow(arena);
}
constexpr auto UpdateRow::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(UpdateRow, _impl_.data_) +
          decltype(UpdateRow::_impl_.data_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(UpdateRow), alignof(UpdateRow), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&UpdateRow::PlacementNew_,
                                 sizeof(UpdateRow),
                                 alignof(UpdateRow));
  }
}
constexpr auto UpdateRow::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UpdateRow_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UpdateRow::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UpdateRow>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UpdateRow::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UpdateRow>(), &UpdateRow::ByteSizeLong,
              &UpdateRow::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UpdateRow, _impl_._cached_size_),
          false,
      },
      &UpdateRow::kDescriptorMethods,
      &descriptor_table_updates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UpdateRow_class_data_ =
        UpdateRow::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL UpdateRow::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UpdateRow_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UpdateRow_class_data_.tc_table);
  return UpdateRow_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
UpdateRow::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    UpdateRow_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::orderbookio::UpdateRow>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .orderbookio.Update data = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateRow, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .orderbookio.Update data = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateRow, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::orderbookio::Update>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void UpdateRow::Clear() {
// @@protoc_insertion_point(message_clear_start:orderbookio.UpdateRow)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UpdateRow::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UpdateRow& this_ = static_cast<const UpdateRow&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UpdateRow::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UpdateRow& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:orderbookio.UpdateRow)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .orderbookio.Update data = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_data_size());
       i < n; i++) {
    const auto& repfield = this_._internal_data().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:orderbookio.UpdateRow)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UpdateRow::ByteSizeLong(const MessageLite& base) {
  const UpdateRow& this_ = static_cast<const UpdateRow&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UpdateRow::ByteSizeLong() const {
  const UpdateRow& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:orderbookio.UpdateRow)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .orderbookio.Update data = 1;
    {
      total_size += 1UL * this_._internal_data_size();
      for (const auto& msg : this_._internal_data()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UpdateRow::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateRow*>(&to_msg);
  auto& from = static_cast<const UpdateRow&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:orderbookio.UpdateRow)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_data()->MergeFrom(
      from._internal_data());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateRow::CopyFrom(const UpdateRow& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:orderbookio.UpdateRow)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateRow::InternalSwap(UpdateRow* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::google::protobuf::Metadata UpdateRow::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateRowWithShares::_Internal {
 public:
  using HasBits =
      decltype(std::declval<UpdateRowWithShares>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UpdateRowWithShares, _impl_._has_bits_);
};

UpdateRowWithShares::UpdateRowWithShares(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UpdateRowWithShares_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:orderbookio.UpdateRowWithShares)
}
PROTOBUF_NDEBUG_INLINE UpdateRowWithShares::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::orderbookio::UpdateRowWithShares& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

UpdateRowWithShares::UpdateRowWithShares(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UpdateRowWithShares& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UpdateRowWithShares_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateRowWithShares* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.row_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.row_)
                : nullptr;
  _impl_.shares_ = from._impl_.shares_;

  // @@protoc_insertion_point(copy_constructor:orderbookio.UpdateRowWithShares)
}
PROTOBUF_NDEBUG_INLINE UpdateRowWithShares::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void UpdateRowWithShares::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, row_),
           0,
           offsetof(Impl_, shares_) -
               offsetof(Impl_, row_) +
               sizeof(Impl_::shares_));
}
UpdateRowWithShares::~UpdateRowWithShares() {
  // @@protoc_insertion_point(destructor:orderbookio.UpdateRowWithShares)
  SharedDtor(*this);
}
inline void UpdateRowWithShares::SharedDtor(MessageLite& self) {
  UpdateRowWithShares& this_ = static_cast<UpdateRowWithShares&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.row_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UpdateRowWithShares::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UpdateRowWithShares(arena);
}
constexpr auto UpdateRowWithShares::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UpdateRowWithShares),
                                            alignof(UpdateRowWithShares));
}
constexpr auto UpdateRowWithShares::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UpdateRowWithShares_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UpdateRowWithShares::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UpdateRowWithShares>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UpdateRowWithShares::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UpdateRowWithShares>(), &UpdateRowWithShares::ByteSizeLong,
              &UpdateRowWithShares::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UpdateRowWithShares, _impl_._cached_size_),
          false,
      },
      &UpdateRowWithShares::kDescriptorMethods,
      &descriptor_table_updates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UpdateRowWithShares_class_data_ =
        UpdateRowWithShares::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL UpdateRowWithShares::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UpdateRowWithShares_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UpdateRowWithShares_class_data_.tc_table);
  return UpdateRowWithShares_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
UpdateRowWithShares::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UpdateRowWithShares, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    UpdateRowWithShares_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::orderbookio::UpdateRowWithShares>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 shares = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateRowWithShares, _impl_.shares_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(UpdateRowWithShares, _impl_.shares_)}},
    // .orderbookio.UpdateRow row = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(UpdateRowWithShares, _impl_.row_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .orderbookio.UpdateRow row = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateRowWithShares, _impl_.row_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 shares = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateRowWithShares, _impl_.shares_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::orderbookio::UpdateRow>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void UpdateRowWithShares::Clear() {
// @@protoc_insertion_point(message_clear_start:orderbookio.UpdateRowWithShares)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(_impl_.row_ != nullptr);
    _impl_.row_->Clear();
  }
  _impl_.shares_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UpdateRowWithShares::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UpdateRowWithShares& this_ = static_cast<const UpdateRowWithShares&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UpdateRowWithShares::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UpdateRowWithShares& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:orderbookio.UpdateRowWithShares)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .orderbookio.UpdateRow row = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.row_, this_._impl_.row_->GetCachedSize(), target,
        stream);
  }

  // uint32 shares = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    if (this_._internal_shares() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_shares(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:orderbookio.UpdateRowWithShares)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UpdateRowWithShares::ByteSizeLong(const MessageLite& base) {
  const UpdateRowWithShares& this_ = static_cast<const UpdateRowWithShares&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UpdateRowWithShares::ByteSizeLong() const {
  const UpdateRowWithShares& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:orderbookio.UpdateRowWithShares)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // .orderbookio.UpdateRow row = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.row_);
    }
    // uint32 shares = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_shares() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_shares());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UpdateRowWithShares::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateRowWithShares*>(&to_msg);
  auto& from = static_cast<const UpdateRowWithShares&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:orderbookio.UpdateRowWithShares)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.row_ != nullptr);
      if (_this->_impl_.row_ == nullptr) {
        _this->_impl_.row_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.row_);
      } else {
        _this->_impl_.row_->MergeFrom(*from._impl_.row_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_shares() != 0) {
        _this->_impl_.shares_ = from._impl_.shares_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateRowWithShares::CopyFrom(const UpdateRowWithShares& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:orderbookio.UpdateRowWithShares)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateRowWithShares::InternalSwap(UpdateRowWithShares* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateRowWithShares, _impl_.shares_)
      + sizeof(UpdateRowWithShares::_impl_.shares_)
      - PROTOBUF_FIELD_OFFSET(UpdateRowWithShares, _impl_.row_)>(
          reinterpret_cast<char*>(&_impl_.row_),
          reinterpret_cast<char*>(&other->_impl_.row_));
}

::google::protobuf::Metadata UpdateRowWithShares::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Updates::_Internal {
 public:
};

Updates::Updates(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Updates_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:orderbookio.Updates)
}
PROTOBUF_NDEBUG_INLINE Updates::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::orderbookio::Updates& from_msg)
      : data_{visibility, arena, from.data_},
        _cached_size_{0} {}

Updates::Updates(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Updates& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Updates_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Updates* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:orderbookio.Updates)
}
PROTOBUF_NDEBUG_INLINE Updates::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : data_{visibility, arena},
        _cached_size_{0} {}

inline void Updates::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Updates::~Updates() {
  // @@protoc_insertion_point(destructor:orderbookio.Updates)
  SharedDtor(*this);
}
inline void Updates::SharedDtor(MessageLite& self) {
  Updates& this_ = static_cast<Updates&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Updates::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Updates(arena);
}
constexpr auto Updates::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Updates, _impl_.data_) +
          decltype(Updates::_impl_.data_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Updates), alignof(Updates), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Updates::PlacementNew_,
                                 sizeof(Updates),
                                 alignof(Updates));
  }
}
constexpr auto Updates::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Updates_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Updates::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Updates>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Updates::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Updates>(), &Updates::ByteSizeLong,
              &Updates::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Updates, _impl_._cached_size_),
          false,
      },
      &Updates::kDescriptorMethods,
      &descriptor_table_updates_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Updates_class_data_ =
        Updates::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL Updates::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Updates_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Updates_class_data_.tc_table);
  return Updates_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
Updates::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Updates_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::orderbookio::Updates>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .orderbookio.UpdateRowWithShares data = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Updates, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .orderbookio.UpdateRowWithShares data = 1;
    {PROTOBUF_FIELD_OFFSET(Updates, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::orderbookio::UpdateRowWithShares>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Updates::Clear() {
// @@protoc_insertion_point(message_clear_start:orderbookio.Updates)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Updates::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Updates& this_ = static_cast<const Updates&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Updates::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Updates& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:orderbookio.Updates)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .orderbookio.UpdateRowWithShares data = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_data_size());
       i < n; i++) {
    const auto& repfield = this_._internal_data().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:orderbookio.Updates)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Updates::ByteSizeLong(const MessageLite& base) {
  const Updates& this_ = static_cast<const Updates&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Updates::ByteSizeLong() const {
  const Updates& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:orderbookio.Updates)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .orderbookio.UpdateRowWithShares data = 1;
    {
      total_size += 1UL * this_._internal_data_size();
      for (const auto& msg : this_._internal_data()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Updates::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Updates*>(&to_msg);
  auto& from = static_cast<const Updates&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:orderbookio.Updates)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_data()->MergeFrom(
      from._internal_data());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Updates::CopyFrom(const Updates& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:orderbookio.Updates)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Updates::InternalSwap(Updates* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::google::protobuf::Metadata Updates::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace orderbookio
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_updates_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
